/*
 * command.h
 *
 *  Created on: May 24, 2018
 *      Author: dmcneill
 */

#ifndef COMMAND_H_
#define COMMAND_H_

#define CMD_NULL 0   // no command

#define CMD_NODE_READY 1
#define CMD_REQ_HT 2
#define CMD_RTN_HT 3
#define CMD_REQ_WIND 4
#define CMD_RTN_WIND 5
#define CMD_REQ_RAIN 6
#define CMD_RTN_RAIN 7
#define CMD_REQ_POWER 8
#define CMD_RTN_POWER 9
#define CMD_REQ_HTP 10
#define CMD_RTN_HTP 11
#define CMD_SET_NODE_ETIME 12
#define CMD_REQ_NODE_ETIME 13
#define CMD_RTN_NODE_ETIME 14
#define CMD_SET_SLEEP 15
#define CMD_REQ_PRESSURE 16
#define CMD_RTN_PRESSURE 17
#define CMD_SET_RFID 18
#define CMD_REQ_NODE_RSSI 19
#define CMD_RTN_NODE_RSSI 20
#define CMD_ACK 21
#define CMD_SET_HUB_ETIME 22
#define CMD_SET_CMDLIST 23
#define CMD_ENDRESPONSE 24
#define CMD_REQ_HUB_RSSI 25
#define CMD_RTN_HUB_RSSI 26
#define CMD_REQ_NODE_SYS 27
#define CMD_RTN_NODE_SYS 28
#define CMD_REQ_HUB_SYS 29
#define CMD_RTN_HUB_SYS 30
#define CMD_CLR_NODE_SYS 31
#define CMD_CLR_HUB_SYS 32
#define CMD_SET_WAKEUP 33
#define CMD_REQ_CLR_RAIN 34
#define CMD_SET_AUTO_CMDLIST 35
#define CMD_REQ_IHT 36
#define CMD_RTN_IHT 37
#define CMD_SET_HUB_RESET 38
#define CMD_SET_NODE_RESET 39
#define CMD_REQ_SIMPLE 40
#define CMD_RTN_SIMPLE 41



// lengths of each command packet
#define LENGTH_CMD_NODE_READY 4
#define LENGTH_CMD_REQ_HT 2
#define LENGTH_CMD_RTN_HT 10
#define LENGTH_CMD_REQ_WIND 2
#define LENGTH_CMD_RTN_WIND 26
#define LENGTH_CMD_REQ_RAIN 3
#define LENGTH_CMD_RTN_RAIN 7
#define LENGTH_CMD_REQ_POWER 2
#define LENGTH_CMD_RTN_POWER 12
#define LENGTH_CMD_REQ_HTP 2
#define LENGTH_CMD_RTN_HTP 18
#define LENGTH_CMD_SET_NODE_ETIME 6
#define LENGTH_CMD_REQ_NODE_ETIME 2
#define LENGTH_CMD_RTN_NODE_ETIME 6
#define LENGTH_CMD_SET_SLEEP 2
#define LENGTH_CMD_REQ_PRESSURE 2
#define LENGTH_CMD_RTN_PRESSURE 10
#define LENGTH_CMD_SET_RFID 4
#define LENGTH_CMD_REQ_NODE_RSSI 2
#define LENGTH_CMD_RTN_NODE_RSSI 5
#define LENGTH_CMD_ACK 2
#define LENGTH_CMD_SET_HUB_ETIME 6
#define LENGTH_CMD_ENDRESPONSE 2
#define LENGTH_CMD_REQ_HUB_RSSI 2
#define LENGTH_CMD_RTN_HUB_RSSI 5
#define LENGTH_CMD_RTN_NODE_SYS 20
#define LENGTH_CMD_REQ_NODE_SYS 2
#define LENGTH_CMD_RTN_HUB_SYS 20
#define LENGTH_CMD_REQ_HUB_SYS 2
#define LENGTH_CMD_CLR_NODE_SYS 2
#define LENGTH_CMD_CLR_HUB_SYS 2
#define LENGTH_CMD_SET_WAKEUP 3
#define LENGTH_CMD_REQ_CLR_RAIN 3
#define LENGTH_CMD_REQ_IHT 2
#define LENGTH_CMD_RTN_IHT 10
#define LENGTH_CMD_SET_HUB_RESET 2
#define LENGTH_CMD_SET_NODE_RESET 2
#define LENGTH_CMD_REQ_SIMPLE 2
#define LENGTH_CMD_RTN_SIMPLE 29


#endif /* COMMAND_H_ */
